// This file was autogenerated by vendor/google-closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../sample/lib/ui/textarea.js', ['ui.Textarea'], ['goog.ui.Component']);
